services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
      args: 
        - VITE_API_URL=/api
        - VITE_SOCKET_URL=http://localhost:8080
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:8
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: